config/routes.rb
Rails.application.routes.draw do

  get '/quotes/search', to: 'quotes#search', as: 'quotes_search'

  resources :quotes

  resources :books

  resources :books, only: [:show]  do
    # nested resource for quotes
    resources :quotes, only: [:new, :show]
  end





  root to: 'application#welcome'
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'callbacks' }
  devise_scope :user do 
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :quotes
    has_many :users, through: :quotes

    validates :author, presence: true 
    validates :name, :presence => true, :uniqueness => true

    accepts_nested_attributes_for :quotes, reject_if: :all_blank

    scope :search_book, ->(book_search) { where("name LIKE ?", "%#{book_search}%") }
    
end

app/models/quote.rb
class Quote < ApplicationRecord
    belongs_to :user
    belongs_to :book

    accepts_nested_attributes_for :book, reject_if: :all_blank

    validates :content, presence: true
    validates :content, length: { minimum: 10 }


    scope :searched, ->(search_term) { where("content LIKE ?", "%#{search_term}%") }

    # scope :searched, ->(search_term) { where(“content LIKE ?", "%#{sanitize_sql_like(search_term)}%”)}
end
 

app/models/user.rb
class User < ApplicationRecord
  has_many :quotes
  has_many :books, through: :quotes
  validates :email, presence: true
  validates :email, uniqueness: true
  validates :password, presence: true 

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable
         
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.username = auth.info.nickname
      user.uid =  auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def welcome   
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    before_action :authenticate_user!
    
      def index
        # @books = Book.all.order(:name)
        if params[:search]
          # binding.pry
          @books = Book.search_book(params[:search])
        else
          @books = Book.all.order(:name)
        end
      end
    
      def show
        @book = Book.find_by(id: params[:id])
      end
    
      def new
        @book = Book.new
      end
    
      def create
        @book = Book.new(book_params)

        @book.save
        
        if @book.save
          redirect_to @book
        else
          render :new
        end
      end
    
      def edit
        @book = Book.find_by(id: params[:id])
      end
    
      def update
        @book = Book.find_by(id: params[:id])
    
        @book.update(book_params)
    
        if @book.save
          redirect_to @book
        else
          render :edit
        end
      end
    
      private
    
      def book_params
        params.require(:book).permit(:name, :author)
      end
    
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        # binding.pry
        sign_in_and_redirect @user
    end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    before_action :authenticate_user!

    def search 
    end

    def index
        if params[:search]
          @quotes = current_user.quotes.searched(params[:search])
        elsif params[:book_id]
          book = current_user.books.find_by(id: params[:book_id])
          if book
            @quotes = book.quotes  
          else
            redirect_to books_path
          end 
        else
          @quotes = current_user.quotes
        end
    end
    
      def show
        @quote = current_user.quotes.find_by(id: params[:id])
      end
    
      def new
          @quote = current_user.quotes.build(book_id: params[:book_id])
      
      end
    
      def create
        @quote = current_user.quotes.build(quote_params)
        if @quote.save
          redirect_to @quote
        else
          render :new
        end
      end
    
      def edit
        @quote = current_user.quotes.find_by(id: params[:id])
      end
    
      def update
        @quote = current_user.quotes.find_by(id: params[:id])
    
        @quote.update(quote_params)
    
        if @quote.save
          redirect_to @quote
        else
          render :edit
        end
      end
    
      def destroy
        @quote = current_user.quotes.find_by(id: params[:id])
        @quote.destroy
        flash[:notice] = "quote deleted."
        redirect_to quotes_path
      end
    
      private
    
      def quote_params
        params.require(:quote).permit(:content, :user_id, :book_id, book_attributes: [:name, :author])
      end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/application/welcome.html.erb
<h1>Enquote</h1>
<h4>
<% if user_signed_in? && current_user.quotes.any?%>
<%= form_tag quotes_path, :method => 'get' do %>   
    <%= text_field_tag :search, params[:search] %>   
    <%= submit_tag "Search", name: nil %> </h4>
<% end %>
<% end %>
</h4>
<div class="photo">
    <img src="https://i1.wp.com/www.lisasell.co.uk/wp-content/uploads/2017/06/BOOKS..png?fit=659%2C318&ssl=1" alt="books">
    <img src="https://elburn.lib.il.us/wp-content/uploads/2017/05/library-services.jpg" alt="library">

</div>
<br>
<h4>“Books are a uniquely portable magic.”
― Stephen King</h4>
 <h4>On Writing: A Memoir of the Craft</h4>
<br>
<h4><%= link_to "Add a Quote", new_quote_path %></h4>

app/views/books/index.html.erb
<h1>Check Out All The Books</h1>
    <h4>
   <%@books.each do |book|%>
        <%= link_to book.name, book_path(book) %><br>
    <% end %>
    </h4>

app/views/books/new.html.erb
<h1>Create a Book</h1>
<%= form_for (@book) do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %><br><br>
  <%= f.label "Author" %>
  <%= f.text_field :author %><br><br>
  <%= f.submit %>
<% end %>

app/views/books/search.html.erb
<h1>Search Books</h1>
<h4>
<%= form_tag books_path, :method => 'get' do %>   
    <%= text_field_tag :search, params[:search] %>   
    <%= submit_tag "Search", name: nil %> </h4>
<% end %>

app/views/books/show.html.erb
<h1><%= @book.name %></h1>
<h4>By: <%= @book.author %></h4>
<br>
<br>
<h2>Quotes from this Book</h2>
<h5>
    <% @book.quotes.each do |quote| %>
        <%= link_to quote.content, book_quote_path(@book, quote) %>
        <br>
        <br>
    <%end%>
    <h4><%= link_to 'Create a new Quote', new_book_quote_path(@book)%></h4>
</h5>

app/views/layouts/_nav.html.erb
<nav>
    <ul>
        <%= link_to "Home", root_path %><br>

        <% if !user_signed_in? %>  
            <%= link_to "Signup", new_user_registration_path %><br>
            <%= link_to "Login", new_user_session_path %><br>
        <% else %>
            <%= current_user.email %><br>
            <%= link_to "My Quotes", quotes_path %><br>
            <%= link_to "All Books", books_path %><br>
            <%=  link_to "Logout", destroy_user_session_path, method: "delete" %>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enquote</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      .photo {
        text-align: center;
        padding: 10px;
        margin: 4px 0 0 4px;
        box-shadow: 0 0 0 4px #fff;
    }
    .photo img {
      width: 300px;
      height: 215px;
      background-size: cover;
      object-fit: cover;
    }
    h2, h4, h1, h5, p {
      text-align: center;
    }
    body {
      padding: 30px;
      font-family: Didot;
      background-image: url(images.unsplash.com/photo-1457369804613-52c61a468e7d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80) repeat;
      <%# background-color: rgb(240,235,216); %>
      <%# opacity: 0.5; %>
    }
    .navigation a {
      color: teal;
    }

    /* div.background {
      background-image: url(images.unsplash.com/photo-1457369804613-52c61a468e7d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80) repeat;
      /* border: 2px solid black; */
    /* }  */
    </style>
  </head>

  <body>

    <%= render 'layouts/nav'%>
    <%= yield %>
  </body>
</html>

app/views/quotes/edit.html.erb
<h1>Change Your Quote</h1>
<br>
<h4>
<%= form_for (@quote) do |f| %>
  <%= f.text_area :content %><br><br>
  <%= f.submit %>
<% end %>
</h4>

app/views/quotes/index.html.erb
<h1>Welcome to Your Quotes</h1>
<br>
<h4>Search Quotes</h4>
<h4>
<%= form_tag quotes_path, :method => 'get' do %>   
    <%= text_field_tag :search, params[:search] %>   
    <%= submit_tag "Search", name: nil %> </h4>
<% end %>

<br>
<br>

<h4>Your  Quotes</h4><br>
    <h4><%@quotes.each do |quote|%>
        <% if !quote.content.nil? %>
            <%= link_to quote.content, quote_path(quote) %><br><br>
        <% end%>
    <% end %>
    </h4>
<br>
<h4>Do you have more inspiration?</h4>
<h4><%= link_to "Add a Quote", new_quote_path %></h4>
<p> Just want to <%= link_to "search", quotes_search_path %>?</p>

app/views/quotes/new.html.erb
<h1>Add a Quote!</h1>

  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>
      <ul>
        <% @quote.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<%if !params[:book_id] %>
    <%= form_for @quote do |f| %>
    <%= f.label "Add Quote:" %><br>
    <%= f.text_area :content, :class => 'form-control' %><br><br>
    <%= f.label "Select the book associated with the quote:" %><br>
    <%= f.collection_select :book_id, Book.all.order(:name), :id, :name, include_blank: true %><br><br>
    <%= f.label "Or Add a book not listed above:" %><br>
    <%= f.fields_for :book, @quote.build_book do |book_form| %>
      <%= book_form.label "Title" %>
      <%= book_form.text_field :name %><br><br>
      <%= book_form.label "Author" %>
      <%= book_form.text_field :author %><br><br>
      <% end %>
    <%= f.submit %>
    <% end %>
<% else  %>
    <%= form_for @quote do |f|%>
    <%= f.hidden_field :book_id %>
    <%= f.label "Add Quote For This Book:" %><br>
    <%= f.text_area :content, :class => 'form-control' %><br><br>
    <%= f.submit %>
    <% end %> 
<% end  %>

app/views/quotes/search.html.erb
<h1>Search Quotes</h1>
<h4>
<%= form_tag quotes_path, :method => 'get' do %>   
    <%= text_field_tag :search, params[:search] %>   
    <%= submit_tag "Search", name: nil %> </h4>
<% end %>

app/views/quotes/show.html.erb
<h1>Quote: 
<h2><%= @quote.content %> - <%= @quote.book.author %> </h2>

<h5><%= @quote.book.name.upcase %></h5>

<p><%= link_to "Edit", edit_quote_path %> | <%=  link_to "Delete", quote_path, method: "delete" %></p>